pageinfo = [[1171929323,2534],
	[1171929299,4441],
	[1196314395,4378],
	[1171929359,3600],
	[1174354255,15710],
	[1171929331,3910],
	[1171929375,6685],
	[1171929283,3452],
	[1245383949,7095],
	[1171929277,3294],
	[1245384091,2236],
	[1245385695,6563]];
pagedata = [ ["./autologin.htm","Auto-login to Windows","﻿Auto-login You can use Rebooter to set and clear the Windows Auto-login feature. By entering your Domain, User name and password then clicking on...",""],
["./autorun.htm","Auto-run applications","﻿Auto-run applications This page gives a brief description of how an application can be setup to run automatically when Windows starts. This is an...",""],
["./commandline.htm","Command line options","﻿Command line options There are three command line options. If no command line option is specified, Rebooter runs in interactive mode. -Reboot Per...",""],
["./contacts.htm","Contacting PassMark Software","﻿Contacting PassMark Software On the Web You can contact PassMark&#8482; on the web at http://www.passmark.com E-Mail For technical support questions, s...",""],
["./copyright.htm","Copyright and License","﻿Copyright &#38; License information PassMark&#174; Software Pty Ltd (‘PassMark’) End User Licence Agreement (‘EULA’) IMPORTANT! PLEASE READ THE FOLLOWING ...",""],
["./cycle.htm","Reboot cycling and looping","﻿Cyclic rebooting This page gives a brief description of how a PC can be set-up to reboot itself in a cycle. Step1 – Select and save Rebooter sett...",""],
["./faq.htm","Problems and FAQ","﻿Frequently Asked Questions (FAQ) Note: See the PassMark&#8482; website (www.passmark.com) for the latest version of the FAQ Q. Why trying to reboot, I ...",""],
["./forcetypes.htm","Forcing a reboot","﻿Forced reboot Three options are available. Ask to close Default value. Each running application is given the chance to block the shutdown of Wind...",""],
["./overview.htm","Introduction and Overview","﻿Rebooter by PassMark Software - Overview Rebooter is a small utility program developed by PassMark­&#8482; Software to help automate the PC hardware te...",""],
["./reboottypes.htm","Reboot and Restart types","﻿Reboots and Restarts There are four options available. Power-off This would shut down the system and turn off the power. The system must support ...",""],
["./systemreq.htm","System requirements","﻿System Requirements 80486 50Mhz or faster Windows 95, 98, Me, NT4, 2000, XP, 2003 server, Vista, Windows 7 16Meg RAM 0.1MB of free hard disk spac...",""],
["./whats_new.htm","What&#39;s new","﻿What new - Version history V1.3.1003 19/June/2009 Fixed a bug where the \"-reboot\" command line option would not set the auto start on system star...",""]];
