pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["add_lockrights.htm","Setting the Lock Pages in Memory right","Setting the Lock Pages in Memory right To use the advanced RAM test, the user needs to be logged in as the administrator and have the &#8220;Lock pages ...",""],
["advnet.htm","Advanced network test","Advanced network test (Applicable to BurnInTest Pro version only) Overview The Advanced Network test allows stability and load testing of up to 12...",""],
["advnetoptions.htm","Advanced Network","Advanced network (Applicable to BurnInTest Pro version only) Select network card(s) to test Network card IP address This list will show the IP of ...",""],
["battery_monitoring.htm","Battery monitoring","Battery monitoring Battery / UPS Monitoring BurnInTest can work with another product from PassMark Software called BatteryMon. BatteryMon allows t...",""],
["bith0037.htm","Contacting PassMark","Contacting PassMark Software On the Web You can contact PassMark on the web at http://www.passmark.com E-Mail For technical support questions, sug...",""],
["bith05bb.htm","3D Graphics Test suite","3D Graphics Test This test creates and animates a 3D image to test the 3D functions of the video card and its associated software. The test create...",""],
["bith0ckk.htm","Machine Identity","Report information (Machine Identity and additional notes) General report information The fields in this section allow the entry of information re...",""],
["bith0fw4.htm","Serial port test","Serial port test (Applicable to BurnInTest Pro version only) Tests the serial communications ports connected to the PC. Up to 64 serial ports may ...",""],
["bith0rqf.htm","Scripts;Creating scripts;sequential testing;","Scripting BurnInTest includes a simple scripting language that allows tests to be executed in a sequence. A PASS/FAIL indication for all of the te...",""],
["bith0u99.htm","RAM test preferences dialog box","Test Preferences – RAM RAM Test mode Standard Test The standard memory test allocates RAM from the Windows operating system. BurnInTest then uses ...",""],
["bith11k5.htm","Save as image","Save as Image This dialog allows the main window (or its contents) to be saved as an image file which can then be imported into other application ...",""],
["bith14ma.htm","USB preferences dialog box","Test Preferences – USB ports (Applicable to BurnInTest Pro version only) Maximum number of USB ports This is the maximum number of USB devices tha...",""],
["bith1j3o.htm","Parallel port preferences dialog box","Test Preferences – Parallel ports (Applicable to BurnInTest Pro version only) Parallel port The communications port that will be used by the paral...",""],
["bith1o6x.htm","Video play test","Video play test This test allows video files to be played as a BurnInTest test. This allows for the detection of numerous error conditions that a ...",""],
["bith1of8.htm","Sound preferences dialog box","Test Preferences – Sound Sound test type Select the type of test you wish to carry out. Wave File, Midi File and MP3 File Browse to select the fil...",""],
["bith1oqh.htm","Memory (RAM) test","Memory Test The Memory test, tests the reliability of the RAM installed in the computer. As BurnInTest runs within windows some of the available R...",""],
["bith1tf5.htm","System Requirements","System Requirements Operating System: BurnInTest 32bit version specific: 32bit versions (x86) of Windows 98, 2000, ME, XP, 2003 server (*) BurnInT...",""],
["bith1tk4.htm","Sound card test","Sound card test This test operates in two different modes. The standard mode verifies that the sound card can play back MP3, wave form audio and M...",""],
["bith21bb.htm","Detailed Error Log file; Error classifications","Detailed Error log history The detailed error log history can be opened from the ‘View / Error log file’ menu. It contains a record of recent erro...",""],
["bith299j.htm","Fault finding procedure","Fault finding What follows is some hints on how go about finding the cause of a particular system instability. (i.e. The system locks up, you get ...",""],
["bith2ciz.htm","Network preferences dialog box","Test Preferences – Network (The Standard Network Test is available in the Standard and Professional editions of BurnInTest. The Advanced Network T...",""],
["bith2lo3.htm","Graphics Tests suite","2D Graphics – Graphics functions This suite contains a number of tests that exercise the standard Windows graphics functions and the video card. L...",""],
["bith2qln.htm","Serial port loop back plug","Serial port loop back plug (Applicable to BurnInTest Pro version only) You can purchase high quality molded loop back plugs from PassMark or you c...",""],
["bith2u26.htm","Temperature and Battery monitoring","Temperature and Battery monitoring Battery monitoring (via BatteryMon) BurnInTest can work with another product from PassMark Software called Batt...",""],
["bith2x6b.htm","Interpreting the results","Interpreting the results This part of the main window displays a summary of all the results of all the tests that are currently running. Test Name...",""],
["bith3gab.htm","Menus","Menu Options File Save report Save the recent results as a text report, HTML report or a customer targeted Test Certificate. See Preparing a Custo...",""],
["bith3kmv.htm","Overview","BurnInTest by PassMark Software - Overview PassMark’s BurnInTest is a software tool that allows all the major sub-systems of a computer to be simu...",""],
["bith3krr.htm","Logging preferences dialog box","Test Preferences – Logging Logging to the Detailed Error log history Errors are automatically logged to the Detailed Error log history. This log i...",""],
["bith3l5x.htm","Command line options","Command line arguments The following are the BurnInTest command line parameters -C [configfilename] Loads the configuration file specified by [con...",""],
["bith3r3t.htm","Version history","What’s new Please see our version history online at http://www.passmark.com/products/bit_history.htm ",""],
["bith3xyf.htm","Multiple test configurations","Maintaining multiple test configurations If you are in the business to testing many different computers then you may benefit from maintaining diff...",""],
["bith3ygi.htm","Error handling preferences dialog box","Test Preferences – Errors Action on Error When BurnInTest detects an error, three options are available. Continue. The error counter is incremente...",""],
["bith40l0.htm","Getting started","Quick start – How to start testing Here’s a summary of the steps to go through to start testing. 1) Use the Configuration, Test Duty Cycles window...",""],
["bith46jw.htm","Serial port preferences dialog box","Test Preferences – Serial ports (Applicable to BurnInTest Pro version only) Adding a serial port To select a serial port for testing, select the C...",""],
["bith4esl.htm","tape drive test","Tape drive test (Applicable to BurnInTest Pro version only) Tests the tape drive connected to the PC. Drives can be connected via the SCSI bus, ID...",""],
["bith4ho3.htm","Common Error messages","Common Test Error Messages When BurnInTest encounters an error during a test run a short description of the error is displayed in the main window....",""],
["bith4js3.htm","Electromagnetic Compliance Testing","Monitor EMC Testing (Applicable to BurnInTest Pro version only) BurnInTest can be used to help with Electromagnetic Compliance Testing (EMC) to AN...",""],
["bith4lid.htm","Reboot cycling","Reboot cycling BurnInTest can be setup so that the PC will reboot itself in a cycle, with test runs occurring between each reboot. BurnInTest uses...",""],
["bith4tis.htm","SMART;Attributes;Drive failure;","What is S.M.A.R.T? S.M.A.R.T. (Self-Monitoring Analysis and Reporting Technology) is an interface between the BIOS and a computers hard disk. It i...",""],
["bith4v3b.htm","Ordering and License","Ordering information Price US Dollars:$49 (Professional version, single user) US Dollars:$24 (Standard version, single user) See the PassMark webs...",""],
["bith4vhv.htm","Test descriptions","Test descriptions Several tests are built into the software. Each of these tests contains one or more sub-tests designed to exercise different asp...",""],
["bith517p.htm","Tape preferences dialog box","Test Preferences – Tape (Applicable to BurnInTest Pro version only) Tape drive The tape drive ID can be entered into this field. Windows normally ...",""],
["bith54by.htm","plug-in test","&#8220;Plugin&#8221; test (Applicable to BurnInTest Pro version only) If you have specialized hardware that BurnInTest does not test, you can write your own t...",""],
["bith55wz.htm","Preferences dialog box","Test Preferences Disk preferences CD preferences Logging preferences Error handling preferences Network preferences Temperature and Battery monito...",""],
["bith57vv.htm","Disk Tests suite","Disk test (Hard disk, Floppy, flash drive) This suite contains a number of tests that exercise the mass storage units (Hard disk or otherwise) con...",""],
["bith592w.htm","MMX, SSE, 3DNow! Test suite","MMX / SSE / 3DNow! Test First some definitions: MMX = Multimedia Extensions SSE = Streaming SIMD extensions SIMD = Single Instruction Multiple Dat...",""],
["bith5cvn.htm","Maths preferences dialog box","Test Preferences – Maths Select maths tests Using the check boxes it is possible to select which maths tests will be performed and which ones will...",""],
["bith5ddf.htm","How to add the Lock pages in memory right","Setting the Lock Pages in Memory right To use the advanced RAM test, the user needs to be logged in as the administrator and have the &#8220;Lock pages ...",""],
["bith5dps.htm","Temperature and Battery preferences dialog box","Test Preferences – Temperature &#38; Battery Temperature monitoring By using a 3 rd party Temperature Monitoring Application and BurnInTest together i...",""],
["bith5i0j.htm","Maths Tests","Maths test This test contains two sub categories (integer and floating point) that contain 8 different tests in total. For each of the integer tes...",""],
["bith5tbb.htm","Example ASCII Log file","Example ASCII text Log file ASCII (Text) log files can be created using the logging option in the Test preferences dialog. The ASCII text log file...",""],
["bith5uaz.htm","Disk preferences dialog box","Test Preferences – Disk Configuring hard disk, Floppy disk and tests for other types of drives These fields and buttons allow the user to select t...",""],
["bith5vck.htm","Parallel port test","Parallel port test (Applicable to BurnInTest Pro version only) Tests the parallel communications port connected to the PC. The parallel port to be...",""],
["bith5yn6.htm","USB port test","USB port test (Applicable to BurnInTest Pro version only) Tests the USB (Universal Serial Bus) communications ports connected to the PC. The USB d...",""],
["bith5zn2.htm","Plugin preferences dialog box","Test Preferences – &#8220;Plugin&#8221; You can specify up to 3 external Plugin test applications. Application Specifies the plugin filename and command line ...",""],
["bith60kz.htm","Precautions","Precautions for thorough and careful testing For a hardware test to be useful several precautions need to be taken. Failure to take into account t...",""],
["bith690t.htm","CD ROM / DVD Test","CD ROM, CD-RW burn and DVD Test Tests the CD-ROM, CD-RW burner and DVD and optionally the sound card (when used with a music CD). This test can be...",""],
["bith6cdr.htm","Audio loopback cable","Audio loopback cable PassMark audio loopback cables contain two 3.5mm gold plated stereo plugs which connect the Audio out and microphone in ports...",""],
["bith6da1.htm","Video play preferences dialog box","Test Preferences – Video Play The Video Playback preferences window allows you to specify up to 3 video files. These may be typed directly into ea...",""],
["bith6n1w.htm","Pre-test preferences dialog box","Test Preferences – Pre-Test Action before running tests You may specify the default behavior of BurnInTest before it begins any test cycle. None (...",""],
["bith6n6s.htm","2DGraphics preferences dialog box","Test Preferences – 2D Graphics (Applicable to BurnInTest Pro version only) There are three options available for 2D video testing in the professio...",""],
["bith6orv.htm","Network test","Network Test BurnInTest provides two different network tests. The standard network test and the advanced network test. The standard network test i...",""],
["bith6plw.htm","CD / DVD preferences dialog box","Test Preferences – CD-RW/DVD CD/DVD drive assignment These fields allow the user to select the CD and DVD drives to be used for the CD/DVD test. C...",""],
["bith6ugi.htm","Timer and test duration preferences dialog box","Test Preferences – Post-Test There are different actions that may be taken based on whether a test Passes or Fails, and whether the test is automa...",""],
["bith6xgz.htm","Advanced Network Test Options;","Advanced Network Test Options (Applicable to BurnInTest Pro version only) Select local network card for testing This list will show the IP of up t...",""],
["bith6xwy.htm","Printer test","Printer Test This test verifies the correct operation of the printer by either sending a standard page of text, or a sending a command file, to th...",""],
["bith76n9.htm","Preparing a Customer Test Certificate","Preparing a Customer Test Certificate A Test Certificate is a report targeted at your customer. It includes your company details, Technician infor...",""],
["bith7igk.htm","Advanced Network Test;","Advanced Network Test (Applicable to BurnInTest Pro version only) Overview The Advanced Network test allows peer to peer testing of NICs and netwo...",""],
["bith7nsi.htm","Parallel port loop back plug","Parallel port loop back plug (Applicable to BurnInTest Pro version only) You can purchase high quality molded loop back plugs from PassMark or you...",""],
["bith84gy.htm","USB port loop back plug","USB port loop back plug (Applicable to BurnInTest Pro version only) USB1 port loop back plug Active USB loopback plugs are the quickest, most effe...",""],
["bith8p6c.htm","Print preferences dialog box","Test Preferences – Printer Standard test The standard test sends pages of text to the default Windows printer. The pages printed by the printer sh...",""],
["bith9035.htm","Problems and FAQ","Frequently Asked Questions (FAQ) See the Passmark web site www.passmark.com for the most up to date version of this FAQ Q. The test run stops afte...",""],
["bith9jlh.htm","CPU affinity preferences dialog box","Test Preferences – CPU (Applicable to BurnInTest Pro version only. Multi-CPU systems only) CPU affinity Normal task scheduling or CPU targeted tes...",""],
["bith9l80.htm","Baseline information dialog box","Test Selection and Duty cycles From this window it is possible to configure the automatic stopping of tests, select the tests to be performed and ...",""],
["bith9myc.htm","Copyright and License","Copyright &#38; License information Ordering information See the information on the Ordering information page for details about the different options ...",""],
["bith9ovh.htm","Video memory testing","2D Graphics – Video memory test This test directly writes, reads and verifies data to the primary display device using the Microsoft DirectDraw in...",""],
["bluetooth.htm","Bluetooth","Bluetooth The Bluetooth test allows a systems Bluetooth adapter to be tested with a remote Bluetooth device. The Bluetooth test can be turned on o...",""],
["commandline.htm","Command line arguments (more options)","Command line arguments (other BurnInTest options) Command line arguments can be used to specify certain BurnInTest options and can be particularly...",""],
["commonerrors.htm","Common test error messages","Common test error messages When BurnInTest encounters an error during a test run a short description of the error is displayed in the main window....",""],
["contacts.htm","Contacting PassMark Software","Contacting PassMark Software On the Web You can contact PassMark on the web at http://www.passmark.com E-Mail For technical support questions, sug...",""],
["copyright.htm","Copyright and License","Copyright &#38; License information Ordering information See the information on the Ordering information page for details about the different options ...",""],
["detailed_log.htm","Event Log","Event Log The Event Log tab displays the recent errors and status messages that have occurred during a test run. It is possible to save a copy of ...",""],
["esata.htm","eSATA","eSATA For eSATA port testing, PassMark suggest using an External Hard Disk with an eSATA interface and the BurnInTest disk test. ",""],
["externally_controlling_burnint.htm","Externally controlling BurnInTest","Externally controlling BurnInTest Controlling BurnInTest from another application Users can run BurnInTest from an external controlling applicatio...",""],
["ex_ascii_log.htm","Example ASCII Log file","Example ASCII text Log file ASCII (Text) log files can be created using the logging option in the Test preferences dialog. The ASCII text log file...",""],
["ex_logging.htm","Example text log","Example text log file PassMark BurnInTest Log file - http://www.passmark.com ======================================================== Date: 05/18/...",""],
["ex_logging_cust.htm","Example Customer Test Certificate","Example Customer Test Certificate ",""],
["ex_logging_html.htm","Example HTML log","Example HTML Log ",""],
["faq.htm","Problems and FAQ","Frequently Asked Questions (FAQ) See the Passmark web site www.passmark.com for the most up to date version of this FAQ We&#39;ve compiled answers to ...",""],
["fault_finding.htm","Fault finding","Fault finding Once you find a fault there are a number of things that can be done to determine the cause of the fault that should enable you to fi...",""],
["firewire.htm","FireWire","FireWire For FireWire port testing, PassMark suggest using an External Hard Disk with a FireWire interface and the BurnInTest disk test. ",""],
["general_comments_about_occasio.htm","General comments about occasional system crashes","General comments about occasional system crashes Problems can occur if your computer runs out of system resources because there is some process or...",""],
["general_usage.htm","General usage","General usage Q. The test run stops after 15 minutes, why ? With the trial version the tests will only run for 15 minutes at a time. After the sof...",""],
["hotkeys.htm","Hotkeys","Hotkeys In addition to the standard menu hotkeys, such as ALT-F to open the File menu, the following Function hotkeys are also available. F1: Open...",""],
["installing_burnintest_to_a_usb.htm","Installing BurnInTest to a USB drive or an optical disk","Installing BurnInTest to a USB drive or an optical disk It is possible to install BurnInTest Professional onto a USB drive or CD/DVD/BD such that ...",""],
["install_and_uninstall.htm","Install and uninstall","Install and uninstall Q. How do I install the software, I need some help to \"Unzip\" the file I have just downloaded. Most of our software is now d...",""],
["language_support.htm","Language support","Language support BurnInTest is in English. However, in BurnInTest V7.0 Non-English character sets are now supported. Examples of this support are:...",""],
["legal.htm","Legal","Copyright &#38; license information Ordering information See the information on the Ordering information page for details about the different options ...",""],
["license_keys.htm","License keys","License keys Q. My License key does not seem to work. Both the User Name and Registration Key must be correctly entered before the software turns ...",""],
["loopback.htm","Serial loop back plugs","Serial port loop back plug (Applicable to BurnInTest Pro version only) You can purchase high quality molded loop back plugs from PassMark or you c...",""],
["loopback_audio.htm","Audio loop back cable","Audio loop back cable (Applicable to BurnInTest Pro version only) PassMark audio loopback cables contain two 3.5mm gold plated stereo plugs which ...",""],
["loopback_par.htm","Parallel loop back plugs","Parallel port loop back plug (Applicable to BurnInTest Pro version only) You can purchase high quality molded loop back plugs from PassMark or you...",""],
["loopback_usb.htm","USB loop back plugs","USB loop back plug (Applicable to BurnInTest Pro version only) USB 2.0 loopback and benchmarking plug USB 2 Loopback plugs can be used to help dia...",""],
["machineid.htm","Report information (Machine identity)","Report information (Machine Identity and additional notes) The fields in this section allow the entry of information related to the identity of th...",""],
["memory_module_spd_data.htm","Example memory module SPD data","Example memory module SPD data Detailed Memory module SPD data is available in a level 2 activity trace log file. This includes information such a...",""],
["menus.htm","Main Menu Options","Main Menu Options File Load Test Configuration A test configuration that has been previously saved to disk can be loaded using this menu option. T...",""],
["menus_2.htm","Pop-up Menu Options","Pop-up Menu Options Context sensitive popup menus are available from the main window tabs using the mouse &#39;Right click&#39;. Depending on the current ...",""],
["mgt_console.htm","Management Console","Management Console For BurnInTest users testing large numbers of systems, the BurnInTest Management Console Web server application allows system i...",""],
["multtestconfig.htm","Maintaining multiple configurations","Maintaining multiple test configurations If you are in the business to testing many different computers then you may benefit from maintaining diff...",""],
["ordering.htm","How to purchase BurnInTest","Ordering information Price US Dollars: $79 (Professional version, single user) US Dollars: $39 (Standard version, single user) See the PassMark we...",""],
["overview.htm","Introduction and Overview","BurnInTest (TM) by PassMark (R) Software - Overview PassMark’s BurnInTest is a software tool that allows all the major sub-systems of a computer t...",""],
["overview_of_display.htm","Overview of display","Overview of display The BurnInTest display comprises the following main components. Menu The menu bar at the top of the main window provides most ...",""],
["precautions.htm","Precautions for thorough and careful testing","Precautions for thorough and careful testing For a hardware test to be useful several precautions need to be taken. Failure to take into account t...",""],
["preferences.htm","Test preferences - Index","Test Preferences Disk preferences Optical Disk preferences Logging preferences Error handling preferences Network preferences Advanced network pre...",""],
["preferences_2d.htm","2D Graphics","2D Graphics The 2D Graphics Test preferences are only included in the BurnInTest Pro version only. 2D Graphics Test There are three options availa...",""],
["preferences_3d.htm","3D Graphics","3D Graphics The 3D Test preferences are only included in the BurnInTest Pro version only. Test window setup (multiple monitor testing) The 3D test...",""],
["preferences_cd.htm","Optical drives","Optical drives These fields allow the user to select the optical drives to be used for the Optical disk test (CD, DVD and BD). Optical Drive Selec...",""],
["preferences_cpu.htm","CPU","CPU Select CPU test types Using the check boxes it is possible to select which CPU test sub categories will be performed and which ones will be sk...",""],
["preferences_disk.htm","Disk","Disk These fields and buttons allow the user to select the drives used in the disk test. This includes tests for hard disks, solid-state drives, f...",""],
["preferences_error.htm","Errors","Errors Action on Error A number of actions can be taken when BurnInTest detects an error Continue The error counter is incremented and testing con...",""],
["preferences_logging.htm","Logging","Logging (reporting) Automatic test results logging (reporting) Test events (such as errors) are always automatically logged to the Event log histo...",""],
["preferences_maths.htm","Test preferences - Maths","Test Preferences – Maths Select math&#39;s tests Using the check boxes it is possible to select which math&#39;s tests will be performed and which ones wi...",""],
["preferences_mgt_console.htm","Management Console","Management Console The Management Console functionality is included in the BurnInTest Pro version only. Management Console settings Manage BurnInT...",""],
["preferences_network.htm","Standard Network Test and Bluetooth","Standard Network Test and Bluetooth Network Test configuration The Standard Network Test is available in the Standard and Professional editions of...",""],
["preferences_parport.htm","Parallel port","Parallel ports The Parallel port test is only included in the BurnInTest Pro version only. Parallel port settings Parallel port The communications...",""],
["preferences_plugin.htm","Plugin","Plugin The Plugin test is only included in the BurnInTest Pro version only. You can specify up to 5 external Plugin test applications . Run at the...",""],
["preferences_pretest.htm","Pre-Test","Pre-Test Action before running tests You may specify the default behavior of BurnInTest before it begins any test cycle. None (start immediately) ...",""],
["preferences_print.htm","Printer","Printer Print test configuration Standard printer test The standard test sends pages of text to the default Windows printer. The pages printed by ...",""],
["preferences_ram.htm","RAM","RAM The RAM Test preferences are only included in the BurnInTest Pro version only. RAM Test mode and test pattern Standard The standard memory tes...",""],
["preferences_serial.htm","Serial ports","Serial ports The Serial port test is only included in the BurnInTest Pro version only. COM Ports selected Remove selected ports To remove one or m...",""],
["preferences_sound.htm","Sound","Sound Sound test type Select the type of test you wish to carry out. Standard Test (Wave File, MIDI and MP3) Browse to select the files which will...",""],
["preferences_tape.htm","Tape","Tape The Tape test is only included in the BurnInTest Pro version only. Tape drive Tape drive ID The tape drive ID can be entered into this field....",""],
["preferences_temp.htm","Temperature","Temperature, Fan speed and Voltage Temperature Monitoring It is possible to monitor, graph and log the temperature of some hardware components whi...",""],
["preferences_timer.htm","Post-Test","Post-Test Action: Testing PASSED / Action: Testing FAILED There are different actions that may be taken based on whether a test Passes or Fails, a...",""],
["preferences_usb.htm","USB ports","USB ports The USB test is only included in the BurnInTest Pro version only. Loopback test Automatically select all USB ports with USB 2.0 Loopback...",""],
["preferences_video_play.htm","Video playback","Video playback Select video playback files Video file 1..4 The Video Playback preferences window allows you to specify up to 4 video files. These ...",""],
["problems_during_testing.htm","Problems during testing","Problems during testing Q. My system crashed after X days of running BurnInTest but after a reboot was OK again. See the general comments below ab...",""],
["quickstart.htm","Quick start guide","Quick start – How to start testing Here’s a summary of the steps to go through to start testing. 1) Use the Configuration, Test Duty Cycles window...",""],
["reboot_cycle.htm","Reboot / restart cycling","Reboot cycling BurnInTest can be setup so that the PC will reboot itself in a cycle, with test runs occurring between each reboot. BurnInTest uses...",""],
["reporting.htm","Reporting","Reporting Q. Can I add my company logo and company information to the BurnInTest test certificate report? Yes. The test certificate introduced in ...",""],
["results.htm","Results - Interpreting the results","Interpreting the results This Burn In Results tab displays a summary of all the results of all the tests that are currently running or have just r...",""],
["saveasimage.htm","Save Window as Image","Save as Image This dialog allows the main window (or its contents) to be saved as an image file which can then be imported into other application ...",""],
["scripting.htm","Scripting a series of tests","Scripting a series of tests BurnInTest includes a simple scripting language that allows a series of tests with different configurations to be exec...",""],
["scripting_test_preferences.htm","Scripting test preferences","Scripting test preferences This section describes scripting many of the user settings available from the BurnInTest Preferences Windows. Notes: Al...",""],
["smart.htm","What is S.M.A.R.T?","What is S.M.A.R.T? S.M.A.R.T. (Self-Monitoring Analysis and Reporting Technology) is an interface between the BIOS and a computers hard disk. It i...",""],
["support.htm","Support","Support Support available is shown below: Problems and FAQ Fault finding Common error messages System requirements Contacting PassMark Software ",""],
["systemreq.htm","System requirements","System requirements Operating System: Windows XP SP3 and later, 2003 Server, Vista, 2008 Server, Windows 7 (*). CPU: CPU support (e.g. SSE2) is re...",""],
["system_information.htm","System Information","System Information The System information tab contains a snapshot of key information about the current system at the time BurnInTest starts: Syste...",""],
["system_requirements.htm","System requirements","System requirements Q. Does BurnInTest run under DOS ? No. There is no version of BurnInTest that runs under DOS. While there are some advantages ...",""],
["temperature.htm","Temperature","Temperature The Temperature tab displays the temperature of the hardware components configured for temperature monitoring during testing. Temperat...",""],
["temperaturemon.htm","Temperature monitoring","Temperature and Battery monitoring Battery monitoring (via BatteryMon) BurnInTest can work with another product from PassMark Software called Batt...",""],
["testcertificate.htm","Preparing a Customer Test Certificate","Preparing a Customer Test Certificate A Test Certificate is a report targeted at your customer. It includes your company details, Technician infor...",""],
["testdescriptions.htm","Overview","Test descriptions There are many different hardware component tests built into the software. Each of these tests contains one or more sub-tests de...",""],
["testing_with_no_operating_syst.htm","Testing with no operating system installed","Testing with no operating system installed Many BurnInTest users can benefit from testing PC hardware when there is no Operating System installed,...",""],
["testsetup.htm","Test selection and duty cycles","Test selection and duty cycles The Test selection and duty cycles window allows: The test auto stop condition to be set. This is based on a test d...",""],
["tests_3dg.htm","3D Graphics test suite","3D Graphics Test [3D] This test creates and animates a 3D image to test the 3D functions of the video card and its associated software. 3D test Ob...",""],
["tests_cdrom.htm","Optical drive test","Optical drive test [CD] A read test of CD, DVD and Blu-ray drives; write test of CD and DVD drives; and a sound card test when used with a music C...",""],
["tests_disk.htm","Disk test suite","Disk test (hard disk, floppy, flash drive) [DISK] This suite contains a number of tests that exercise the mass storage units (hard disk or otherwi...",""],
["tests_emc.htm","Monitor EMC testing","Monitor EMC Testing [2D] (Applicable to BurnInTest Pro version only) BurnInTest can be used to help with Electromagnetic Compliance Testing (EMC) ...",""],
["tests_graphics.htm","2D graphics - graphics functions","2D Graphics – Graphics functions [2D] This suite contains a number of tests that exercise the standard Windows graphics functions and the video ca...",""],
["tests_maths.htm","CPU test","CPU Test The CPU test exercises and verifies a wide range of CPU instructions, at user specified loads. The user selectable sub-categories of the ...",""],
["tests_memory.htm","RAM test","Memory Test [MEMORY] The Memory test, tests the reliability of the RAM installed in the computer. As BurnInTest runs within windows some of the av...",""],
["tests_mmx.htm","CPU - MMX / SSE / 3DNow! test suite","MMX / SSE / 3DNow! Test [MMX] First some definitions: MMX = Multimedia Extensions SSE = Streaming SIMD extensions SIMD = Single Instruction Multip...",""],
["tests_network.htm","Network test","Network Test [NETWORK] BurnInTest provides two different network tests. The standard network test and the advanced network test. The standard netw...",""],
["tests_parport.htm","Parallel port test","Parallel port test [PARALLEL] (Applicable to BurnInTest Pro version only) Tests the parallel communications port connected to the PC. The parallel...",""],
["tests_plugin.htm","Plug-in test","&#8220;Plugin&#8221; test [PLUGIN] (Applicable to BurnInTest Pro version only) If you have specialized hardware that BurnInTest does not test, you can write y...",""],
["tests_printer.htm","Printer Test","Printer Test [PRINTER] This test verifies the correct operation of the printer by either sending a standard page of text, or a sending a command f...",""],
["tests_serialport.htm","Serial port test","Serial port test [SERIAL] (Applicable to BurnInTest Pro version only) Tests the serial communications ports connected to the PC. Up to 64 serial p...",""],
["tests_sound.htm","Sound Card","Sound card test [SOUND] This test operates in two different modes. The standard mode verifies that the sound card can play back MP3, wave form aud...",""],
["tests_tape.htm","Tape drive testing","Tape drive test [TAPE] (Applicable to BurnInTest Pro version only) Tests the tape drive connected to the PC. Drives can be connected via the SCSI ...",""],
["tests_usb.htm","USB port test","USB port test [USB] (Applicable to BurnInTest Pro version only) Tests the USB (Universal Serial Bus) communications ports connected to the PC. The...",""],
["tests_videomem.htm","2D graphics - video memory","2D Graphics – Video memory test [2D] This test directly writes, reads and verifies data to the primary display device using the Microsoft DirectDr...",""],
["tests_video_play.htm","Video play","Video play test [VIDEO] This test allows video files to be played as a BurnInTest test. This allows for the detection of numerous error conditions...",""],
["test_automation.htm","Test Automation","Test Automation Q. Is there anyway that BurnInTest can be used in an automated fashion, on a production line ? There are a number of features buil...",""],
["test_automation_and_productivi.htm","Test automation and productivity","Test automation and productivity BurnInTest provides a number of features to facilitate test automation and improve productivity. These include: M...",""],
["test_cd_and_test_dvd_set.htm","Optical drive test media","Optical drive test media High Quality Data CDs, Dual-Layer DVDs and Dual-Layer BDs for Testing CD, DVD and Blu-ray Drives This optical drive test ...",""],
["test_descriptions.htm","Test descriptions","Test descriptions There are many different hardware component tests built into the software. Each of these tests contains one or more sub-tests de...",""],
["test_hardware.htm","Test Hardware","Test Hardware Enter topic text here. ",""],
["test_hardware2.htm","Test Hardware","Test Hardware Enter topic text here. ",""],
["test_hardware3.htm","Test hardware","Test hardware Testing system components may require additional hardware. This includes: Sound test Audio loopback cable Disk test eSATA FireWire O...",""],
["test_preferences.htm","Selecting Test Preferences","Selecting Test Preferences Test Preference Windows The Test Preference Windows allow the detailed configuration of each test type, such as the CPU...",""],
["test_reporting.htm","Test reporting","Test reporting System information, test events, test results and temperature can by saved in test reports. Reports can be a number of different fo...",""],
["test_setup_and_information.htm","Test setup and information","Test setup and information Q. I have a quad core/ dual core/dual CPU system, does BurnInTest test all CPUs ? Yes. BurnInTest starts test threads f...",""],
["understanding_the_display.htm","Understanding the display","Understanding the display The BurnInTest display comprises the following main components. Menu The menu bar at the top of the main window provides...",""],
["versionhistory.htm","What&#39;s new","What’s new Please see our version history online at http://www.passmark.com/products/bit_history.htm ",""]];
